#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'oficina-api'
primary_region = 'gru'

[build]

[processes]
  app = 'npm start'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 3000
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  ports = []
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  processes = ['app']
